language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xsltproc libxml2-utils
  - xsltproc --version
  
script:
  - cd arr
  - chmod +x build_make_includes
  - ./build_make_includes
  - make clean
  - make html epub

deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: a1nsARHuY78JJEMGRT/wU5c+EbcgA4rMmIZRVb+ra4OrWE1D9M7H1zcULUL34MadOAkvltPwkIP0v8tnknyj9eMfZL1okkXeLNxvMQiUVrYCcgHlTsI0mxZwFDET+noFM4ZgDw+zwheBanlOmCGX5IR78xaFk4lp9IbNxHgZeZTEh+57hmQQcmiaxpMnq6U53Vxb4QqhZUJu8WPNBL1Ddn8Z2hqJWu8qM1YwWMp3dZMUfzAm+WWaaY3rhTBZRudXhLyhevSGZJU4mruem7nUP0ge+FZl8BarmLoBJeFnKgkDR/bvScOrqNYsNkxd53SRLDi6lC5uvFt0nJ0vLyG7uFGWBXUQ1VFhFTd5CXgpCEWi504GCw/AR4vB8pUCVmW3/2IIFhvaQMpU9fR0puSJBmQgSOXvYSF9hIUvojVK7XEAhT2+2FBan7IsSsepxuFdtlIKtSLrejtSqFI/4eagfK+SN0cUfxQ+3O7pWIBv5wPYdB5IdnUxS378lqFVBbEmO7R19o56afp9XhT8X1YCEWPUoAau5ao/UnY0FFLtStnPrADwEehPonepAElnUV81zYcSaVtQNPUx9paGAvok27X9ULgngQMTh0x5H55WNcv3cbjyOMxvc8IMAmHV0HxOawSksuZgGqIsI5WogsvJGDRC2K5a6tzIJfzLFeNyKh4=
    bucket: book.arr.org.au
    local_dir: html_chunked_ajax
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: a1nsARHuY78JJEMGRT/wU5c+EbcgA4rMmIZRVb+ra4OrWE1D9M7H1zcULUL34MadOAkvltPwkIP0v8tnknyj9eMfZL1okkXeLNxvMQiUVrYCcgHlTsI0mxZwFDET+noFM4ZgDw+zwheBanlOmCGX5IR78xaFk4lp9IbNxHgZeZTEh+57hmQQcmiaxpMnq6U53Vxb4QqhZUJu8WPNBL1Ddn8Z2hqJWu8qM1YwWMp3dZMUfzAm+WWaaY3rhTBZRudXhLyhevSGZJU4mruem7nUP0ge+FZl8BarmLoBJeFnKgkDR/bvScOrqNYsNkxd53SRLDi6lC5uvFt0nJ0vLyG7uFGWBXUQ1VFhFTd5CXgpCEWi504GCw/AR4vB8pUCVmW3/2IIFhvaQMpU9fR0puSJBmQgSOXvYSF9hIUvojVK7XEAhT2+2FBan7IsSsepxuFdtlIKtSLrejtSqFI/4eagfK+SN0cUfxQ+3O7pWIBv5wPYdB5IdnUxS378lqFVBbEmO7R19o56afp9XhT8X1YCEWPUoAau5ao/UnY0FFLtStnPrADwEehPonepAElnUV81zYcSaVtQNPUx9paGAvok27X9ULgngQMTh0x5H55WNcv3cbjyOMxvc8IMAmHV0HxOawSksuZgGqIsI5WogsvJGDRC2K5a6tzIJfzLFeNyKh4=
    bucket: book.arr.org.au
    local_dir: epub3
    upload_dir: epub
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: a1nsARHuY78JJEMGRT/wU5c+EbcgA4rMmIZRVb+ra4OrWE1D9M7H1zcULUL34MadOAkvltPwkIP0v8tnknyj9eMfZL1okkXeLNxvMQiUVrYCcgHlTsI0mxZwFDET+noFM4ZgDw+zwheBanlOmCGX5IR78xaFk4lp9IbNxHgZeZTEh+57hmQQcmiaxpMnq6U53Vxb4QqhZUJu8WPNBL1Ddn8Z2hqJWu8qM1YwWMp3dZMUfzAm+WWaaY3rhTBZRudXhLyhevSGZJU4mruem7nUP0ge+FZl8BarmLoBJeFnKgkDR/bvScOrqNYsNkxd53SRLDi6lC5uvFt0nJ0vLyG7uFGWBXUQ1VFhFTd5CXgpCEWi504GCw/AR4vB8pUCVmW3/2IIFhvaQMpU9fR0puSJBmQgSOXvYSF9hIUvojVK7XEAhT2+2FBan7IsSsepxuFdtlIKtSLrejtSqFI/4eagfK+SN0cUfxQ+3O7pWIBv5wPYdB5IdnUxS378lqFVBbEmO7R19o56afp9XhT8X1YCEWPUoAau5ao/UnY0FFLtStnPrADwEehPonepAElnUV81zYcSaVtQNPUx9paGAvok27X9ULgngQMTh0x5H55WNcv3cbjyOMxvc8IMAmHV0HxOawSksuZgGqIsI5WogsvJGDRC2K5a6tzIJfzLFeNyKh4=
    bucket: book-test.arr.org.au
    local_dir: html_chunked_ajax
    skip_cleanup: true
    acl: public_read
    on:
      all_branches: true
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: a1nsARHuY78JJEMGRT/wU5c+EbcgA4rMmIZRVb+ra4OrWE1D9M7H1zcULUL34MadOAkvltPwkIP0v8tnknyj9eMfZL1okkXeLNxvMQiUVrYCcgHlTsI0mxZwFDET+noFM4ZgDw+zwheBanlOmCGX5IR78xaFk4lp9IbNxHgZeZTEh+57hmQQcmiaxpMnq6U53Vxb4QqhZUJu8WPNBL1Ddn8Z2hqJWu8qM1YwWMp3dZMUfzAm+WWaaY3rhTBZRudXhLyhevSGZJU4mruem7nUP0ge+FZl8BarmLoBJeFnKgkDR/bvScOrqNYsNkxd53SRLDi6lC5uvFt0nJ0vLyG7uFGWBXUQ1VFhFTd5CXgpCEWi504GCw/AR4vB8pUCVmW3/2IIFhvaQMpU9fR0puSJBmQgSOXvYSF9hIUvojVK7XEAhT2+2FBan7IsSsepxuFdtlIKtSLrejtSqFI/4eagfK+SN0cUfxQ+3O7pWIBv5wPYdB5IdnUxS378lqFVBbEmO7R19o56afp9XhT8X1YCEWPUoAau5ao/UnY0FFLtStnPrADwEehPonepAElnUV81zYcSaVtQNPUx9paGAvok27X9ULgngQMTh0x5H55WNcv3cbjyOMxvc8IMAmHV0HxOawSksuZgGqIsI5WogsvJGDRC2K5a6tzIJfzLFeNyKh4=
    bucket: book-test.arr.org.au
    local_dir: epub3
    upload_dir: epub
    skip_cleanup: true
    acl: public_read
    on:
      all_branches: true
