language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xsltproc
  - xsltproc --version
  
script:
  - cd arr
  - chmod +x build_make_includes
  - ./build_make_includes
  - make clean
  - make html epub

deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: kjzbzNDV/5l0cRKGzGeqUu0ZUwM3ZaskRUXPVg9vHWWbY7G9NmqTvCyJpciYav7EPSz7EuiBiu5VNw2rxH/eDbXueAyV9uqISra1FFizRjWsRRddgsxlA95Lo7fwOxDvUZXIs3CV1TncD9erFHv6hJJpcsKF+20cXoGYn92XouHCMzvA/TYLMpz3hGWB/nDVTT805hyNNSR+/yjbqlfVxXrXSLmhv8WKICZIwl5EXe5YkX9dG++aqB+bbiBfBPZvXheHo+t6ijeJUgjHhNPbLFfTt4BCTwCloWOSwScfaCya19KvhE0Da8lGZzxDGvCwMIEye0NCwa5uaAqjoVGI7hx5szVTjPlTX6nvYnBxRv7o5kZRv8oA8X1vGsQUUMxZ0tPZMfCmnHUhuQ0erDfKB6rPGxiaXAwml1KRraeefhQ+mE+p/jIOTIqcOpVx/+HFd00fnQPZNh/NhDwPnzuE52PgatWesnmFXT6hKjVlxhj80gnL5kIaz9JIOuzDTeziFRAhN6t4hAmR0Z1N0xvDlBtD9val2CTpfHocZg3Sw/bBjATmr7fUWt46ZsBms6W5hCNcm0/lse9o4tAMGW/UEpGT/kjiKsm+nTI/kyjW6iba2P7jQzXtV79YuOkbb6NJl+JRFmE7h0+yDrLrGdXVrJeTxif5HM3VwVzQyFQWoLE=
    bucket: rainfall
    local_dir: html_chunked
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJNP7CBWOTGKNM76Q
    secret_access_key:
      secure: kjzbzNDV/5l0cRKGzGeqUu0ZUwM3ZaskRUXPVg9vHWWbY7G9NmqTvCyJpciYav7EPSz7EuiBiu5VNw2rxH/eDbXueAyV9uqISra1FFizRjWsRRddgsxlA95Lo7fwOxDvUZXIs3CV1TncD9erFHv6hJJpcsKF+20cXoGYn92XouHCMzvA/TYLMpz3hGWB/nDVTT805hyNNSR+/yjbqlfVxXrXSLmhv8WKICZIwl5EXe5YkX9dG++aqB+bbiBfBPZvXheHo+t6ijeJUgjHhNPbLFfTt4BCTwCloWOSwScfaCya19KvhE0Da8lGZzxDGvCwMIEye0NCwa5uaAqjoVGI7hx5szVTjPlTX6nvYnBxRv7o5kZRv8oA8X1vGsQUUMxZ0tPZMfCmnHUhuQ0erDfKB6rPGxiaXAwml1KRraeefhQ+mE+p/jIOTIqcOpVx/+HFd00fnQPZNh/NhDwPnzuE52PgatWesnmFXT6hKjVlxhj80gnL5kIaz9JIOuzDTeziFRAhN6t4hAmR0Z1N0xvDlBtD9val2CTpfHocZg3Sw/bBjATmr7fUWt46ZsBms6W5hCNcm0/lse9o4tAMGW/UEpGT/kjiKsm+nTI/kyjW6iba2P7jQzXtV79YuOkbb6NJl+JRFmE7h0+yDrLrGdXVrJeTxif5HM3VwVzQyFQWoLE=
    bucket: rainfall
    local_dir: epub3
    upload_dir: epub
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
