language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xslt-proc
  
script:
  - cd arr
  - chmod +x build_make_includes
  - ./build_make_includes
  - make clean
  - make html epub
