language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xsltproc
  - xsltproc --version
  
script:
  - cd arr
  - chmod +x build_make_includes
  - ./build_make_includes
  - make clean
  - make html epub

deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJ3LDG6WWT3POGVCA
    secret_access_key:
      secure: CSQ2bRo+OkVljOWM4v154jaI/xGI0QKGGItcnznoBTprSaCeN6vczbIKvnIKwAnS3jx5P/U27TSUsynGewCWb0Uaucm9XbkusCv0Fu9Pxvoogvc5CU2ayuQMeKpY8vA7Eh+32Xh5P16nSEK+ROtV6wuDASJFcTOTPrws4dsLze+/JF+y7lTwIHst5ZeFWtpAfse6pnHIkroeHwm9YfQAb7WCBjbdmJ/HJxTK+lGeBAKDQoHR4jESIBC8EnUKkxPsmA+9JaWpjTir/RnaojYiVjKRc73E/F3BgTekulJ75DhkZlkR28i4E8FUPnRelzbETq1yDcF+UOtgL3H+I9gg9hDTJDCC59Xen/sljvgs2Oka71crh9BA+O7X8uHmg00FcYDJnFriU/L71F/KL5b5zRYlDtJyqf8SEgU71jsx1Xvcv0B5p3vy7B94ALavQgeqOMCYzrXqYXWUAoRhO2t0kQ6hbU0kQpq0EMpBp3+341GTMuu6VX0Hy+BDPGltRn/0FOaDF+txEMS+pdF2vm65IhAjdZeZ89BkcIIYtJuvw6dnzbgZ2pr0Ps7L9l3sfD4Yfmr7kBKE9FUE25nb1FrEeKukTcORVtdnZu09N0F8qNv/8c6/B7AhPQZGAxhfxNQAOMXdXShA3PNns+M7FO+TJo3nbsc3X+zMZ85B+dhniQg=
    bucket: rainfall
    local_dir: html_chunked
    upload_dir: /
    skip_cleanup: true
    on:
      branch: master
