# This is a Makefile fragment, which is expected to be included by the
# locale-specific Makefiles located at ../LOCALE_CODE/Makefile .  As a result,
# the relative paths contained within are relative to the LOCALE_CODE
# directory, and *not* to the tools directory, where this file itself resides.

include ../../tools/Makefile.base-vars
NAME = arr_style_guide
OUTNAME = arr_style_guide
DIR = .
include ../../tools/Makefile.base-rules
