<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:arrmap="http://www.arr.org.au/arrmap">
	<arrmap:map>
		<entry key='aggregated database' xslt=''></entry>
		<entry key='ancient text' xslt=''></entry>
		<entry key='artwork' xslt=''></entry>
		<entry key='audiovisual material' xslt=''></entry>
		<entry key='bill' xslt=''></entry>
		<entry key='blog' xslt=''></entry>
		<entry key='book' xslt='monograph'>monograph</entry>
		<entry key='book section' xslt='contrs_mg'>contribution</entry>
		<entry key='case' xslt=''></entry>
		<entry key='catalog' xslt=''></entry>
		<entry key='chart or table' xslt=''></entry>
		<entry key='classical work' xslt=''></entry>
		<entry key='computer program' xslt=''></entry>
		<entry key='conference paper' xslt='contrs_mg'>contribution</entry>
		<entry key='conference proceedings' xslt='contrs_mg'>contribution</entry>
		<entry key='dataset' xslt=''></entry>
		<entry key='dictionary' xslt=''></entry>
		<entry key='edited book' xslt='monograph'>monograph</entry>
		<entry key='electronic article' xslt='elect_serial_entire'>serial</entry>	
		<entry key='electronic book' xslt='elect_serial_entire'>serial</entry>
		<entry key='electronic book section' xslt='elect_serial_article'>article</entry>
		<entry key='encyclopedia' xslt='monograph'>monograph</entry>
		<entry key='equation' xslt=''></entry>
		<entry key='figure' xslt=''></entry>
		<entry key='film or broadcast' xslt=''></entry>
		<entry key='generic' xslt=''></entry>
		<entry key='government document' xslt=''></entry>
		<entry key='grant' xslt=''></entry>
		<entry key='hearing' xslt=''></entry>
		<entry key='journal article' xslt='article_serials'>article</entry>
		<entry key='legal rule or regulation' xslt=''></entry>
		<entry key='magazine article' xslt='article_serials'>article</entry>
		<entry key='manuscript' xslt=''></entry>
		<entry key='map' xslt=''></entry>
		<entry key='music' xslt=''></entry>
		<entry key='newspaper article' xslt=''></entry>
		<entry key='online database' xslt='elect_serial_entire'>serial</entry>
		<entry key='online multimedia' xslt='elect_serial_entire'>serial</entry>
		<entry key='pamphlet' xslt=''></entry>
		<entry key='patent' xslt=''></entry>
		<entry key='personal communication' xslt=''></entry>
		<entry key='report' xslt='monograph'>monograph</entry>
		<entry key='serial' xslt='serials'>serial</entry>
		<entry key='standard' xslt=''></entry>
		<entry key='statute' xslt=''></entry>
		<entry key='thesis' xslt='monograph'>monograph</entry>
		<entry key='unpublished work' xslt=''></entry>
		<entry key='web page' xslt='elect_serial_entire'>serial</entry>

	</arrmap:map>
</xsl:stylesheet>


