name: Build and Deploy Test Code

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    # Build the epub for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build pre-requisites
        run: sudo apt-get update && sudo apt-get install -y make zip libxml2-utils xsltproc

      - name: build document
        run: cd arr && chmod +x build_make_includes && ./build_make_includes && make clean && make html epub

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'

      - name: Sync epub
        run: aws s3 cp --acl public-read ./arr/epub3/arr.epub "s3://${{ vars.AWS_BUCKET_TEST }}/epub/arr.epub"

      - name: Sync HTML
        run: aws s3 cp --acl public-read --recursive ./arr/html_chunked_ajax/ "s3://${{ vars.AWS_BUCKET_TEST }}/"
